### PR TITLE
added count to mp algorithms

### PR DESCRIPTION
**Pull request by quazuo**

### CODE REVIEW

File: test/gtest/common/count.cpp [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+// Fixture
+template <typename T> class Count : public testing::Test {
+protected:
+};
+
+TYPED_TEST_SUITE(Count, AllTypes);
+
+TYPED_TEST(Count, BasicFirstElem) {
+  Ops1<TypeParam> ops(10);
```
Comment (mateuszpn) [inline test/gtest/common/count.cpp:15]: Fill the vector with values, directly, eg.:
```  
std::vector<int> vec{1, 4, 2, 4, 3, 4, 7, 8, 4, 10, 3, 8, 0, 6, 13, 4};
ops.vec = vec;
xp::copy(ops.vec, ops.dist_vec.begin());
```

File: include/dr/mp/algorithms/count.hpp [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+template <dr::distributed_range DR> auto count_if(DR &&dr, auto &&pred) {
+  return __detail::count_if(0, false, dr, pred);
+}
+
+//
+// Iterators
+//
+
+// range, elem, w/wo root
+
```
Comment (mateuszpn) [inline include/dr/mp/algorithms/count.hpp:134]: Should be implemented as _niebloid_ - compare implementation on [std::ranges::count, std::ranges::count_if](https://en.cppreference.com/w/cpp/algorithm/ranges/count), or implementations within dr, eg. mp::views::enumerate

File: include/dr/mp/algorithms/count.hpp [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+inline auto add_counts(rng::forward_range auto &&r) {
+  rng::range_difference_t<decltype(r)> zero{};
+
+  return std::accumulate(rng::begin(r), rng::end(r), zero);
+}
+
+inline auto std_count_if(rng::forward_range auto &&r, auto &&pred) {
+  using count_type = rng::range_difference_t<decltype(r)>;
+
+  if (rng::empty(r)) {
```
Comment (mateuszpn) [inline include/dr/mp/algorithms/count.hpp:18]: This conditional is redundant in std and dpl version. Please do the check before deciding between std and dpl.
Then you have only single call within std/dpl_count_if - remove the functions, do it inline

File: include/dr/mp/algorithms/count.hpp [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+
+  if (rng::empty(dr)) {
+    return count_type{};
+  }
+
+  if (aligned(dr)) {
+    dr::drlog.debug("Parallel count\n");
+
+    // Count within the local segments
+    auto count = [=](auto &&r) {
```
Comment (mateuszpn) [inline include/dr/mp/algorithms/count.hpp:57]: Consider moving the lambda outside the count_if function

**Review by mateuszpn — CHANGES_REQUESTED** [review]

File: include/dr/mp/algorithms/count.hpp (hunk 4 above)
Comment (quazuo) [reply include/dr/mp/algorithms/count.hpp:57]: Some kind of lambda still has to stay here as we need something to pass to `rng::views::transform`. If all of the lambda's code were moved to a separate function, then it would have to take a predicate as a parameter, which would in turn require a new lambda with its only purpose being to pass `pred` to that function. I don't really see a nice solution that would nicely move the lambda outside, unless I'm missing something here

File: include/dr/mp/algorithms/count.hpp (hunk 2 above)
Comment (quazuo) [reply include/dr/mp/algorithms/count.hpp:134]: Can you please elaborate on this a bit more? Although I read up a bit on niebloids (as I've never encountered them before), I still don't really get what you mean in this context. What exactly should here be implemented as a niebloid, and more importantly why?

**Review by mateuszpn — DISMISSED** [review]
Thanks for applying my comments. Yet another issues - small in the implementation, more general in tests.

File: test/gtest/common/count.cpp [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+
+  EXPECT_EQ(std::count_if(ops.vec.begin(), ops.vec.end(), pred),
+            xp::count_if(ops.dist_vec, pred));
+}
+
+TYPED_TEST(Count, FirstElemsIf) {
+  Ops1<TypeParam> ops(20);
+  auto pred = [=](auto &&v) { return v < 5; };
+
+  EXPECT_EQ(std::count_if(ops.vec.begin(), ops.vec.end(), pred),
```
[the remark this answers is not in the document]
Comment (quazuo) [reply test/gtest/common/count.cpp:66]: Thanks, I must have misunderstood the source code for `Ops1` -- fixed it now. I applied changes as per your suggestions and also added another bonus test. I hope all is good now!

File: include/dr/mp/algorithms/count.hpp [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+template <dr::distributed_range DR>
+auto count_if(std::size_t root, bool root_provided, DR &&dr, auto &&pred) {
+  using count_type = rng::range_difference_t<decltype(dr)>;
+  auto comm = mp::default_comm();
+
+  if (rng::empty(dr)) {
+    return count_type{};
+  }
+
+  if (aligned(dr)) {
```
Comment (lslusarczyk) [inline include/dr/mp/algorithms/count.hpp:42]: One range is always aligned with itself. Remove this condition and "else" branch.

**Review by lslusarczyk — CHANGES_REQUESTED** [review]
Mateusz comments applied well.
One more comment. Rest OK.

**Review by lslusarczyk — APPROVED** [review]

**Comment by lslusarczyk** [comment]
@quazuo , please merge this change with latest changes on the main, because you need to catch latest changes in CI

**Comment by lslusarczyk** [comment]
Now mp-tests do not link.
```
/usr/bin/ld: /tmp/icpx-d64b1ab94b/all-f158ad.o: in function `oneapi::dpl::__ranges::__select_backend(oneapi::dpl::execution::v1::sequenced_policy)':
all-fdd6ea.cpp:(.text+0x0): multiple definition of `oneapi::dpl::__ranges::__select_backend(oneapi::dpl::execution::v1::sequenced_policy)'; /tmp/icpx-d64b1ab94b/mp-tests-fac318.o:mp-tests-0cb7bc.cpp:(.text+0x0): first defined here
```
Is this problem in our code, your PR, or again in oneDPL?

**Comment by lslusarczyk** [comment]
> Now mp-tests do not link.
> 
> ```
> /usr/bin/ld: /tmp/icpx-d64b1ab94b/all-f158ad.o: in function `oneapi::dpl::__ranges::__select_backend(oneapi::dpl::execution::v1::sequenced_policy)':
> all-fdd6ea.cpp:(.text+0x0): multiple definition of `oneapi::dpl::__ranges::__select_backend(oneapi::dpl::execution::v1::sequenced_policy)'; /tmp/icpx-d64b1ab94b/mp-tests-fac318.o:mp-tests-0cb7bc.cpp:(.text+0x0): first defined here
> ```
> 
> Is this problem in our code, your PR, or again in oneDPL?

Not a problem with this PR but general in DR or oneDPL. The same failure is seen in https://github.com/oneapi-src/distributed-ranges/pull/833

**Comment by lslusarczyk** [comment]
@quazuo , please again merge this change with latest changes on the main. Timeouts were increased and CI should pass on your change now
